name: "ServerChan Message Test"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14.x'

    - name: Send Message
      run: curl https://sc.ftqq.com/${{secrets.SCKEY}}.send?text=测试标题&desp=测试内容