name: "ServerChan Message Test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14.x'

    - name: Send Message
      run: |
            npm install
            npm run send 测试标题 测试内容